# Generated by Django 3.2.5 on 2021-07-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={},
        ),
    ]
